### ISSUE TITLE
As a coder write a script to spawn random objects on the horizontal axis

### ISSUE THREAD

**Issue by HeatherBishop** [UoSGamesGroups/first-semester-l4-5-group-3#54]
4 hours.

**Comment by Nat-Berger** [comment]
Suggested an idea about changing the code so that it isn't random but instead have a set strategy where the player can learn the level instead of passing it blind first time. 
[CodeForProject.txt](https://github.com/UoSGamesGroups/first-semester-l4-5-group-3/files/607354/CodeForProject.txt)

Edit: 4 hours (included in making an art asset to test if it worked and other code complimenting the use of it)
